### ISSUE TITLE
wxWidgets/Qt occasional crash when file open dialog closes

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/motor-task-prototype#80]
Occasionally get this crash on linux - not consistently reproducible, looks like some issue with correctly initializing wxWidgets

Also strange that it seems to call QtWidgets.QFileDialog instead of the wxWidgets equivalent

Should check if it also happens sometimes on windows

```
pygame 2.1.2 (SDL 2.0.16, Python 3.9.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /tmp/pip-install-9ngm6sal/wxpython_0f8c5d902fc246a9bb48e9905e41957d/ext/wxWidgets/src/gtk/dialog.cpp(196) in EndModal(): either wxDialog:EndModal called twice or ShowModal wasn't called

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/liam/.pyenv/versions/3.9.7/bin/motor_task_prototype", line 8, in <module>
    sys.exit(main())
  File "/home/liam/SSC/motor-task-prototype/src/motor_task_prototype/__main__.py", line 11, in main
    user_choices = mtp.setup()
  File "/home/liam/SSC/motor-task-prototype/src/motor_task_prototype/setup.py", line 122, in setup
    filename = fileOpenDlg(allowed="Psydat files (*.psydat)")
  File "/home/liam/.pyenv/versions/3.9.7/lib/python3.9/site-packages/psychopy/gui/qtgui.py", line 580, in fileOpenDlg
    filesToOpen = QtWidgets.QFileDialog.getOpenFileNames(parent=None,
SystemError: <built-in function getOpenFileNames> returned a result with an error set
1.5493  WARNING         We strongly recommend you activate the PTB sound engine in PsychoPy prefs as the preferred audio engine. Its timing is vastly superior. Your prefs are currently set to use ['sounddevice', 'PTB', 'pyo', 'pygame'] (in that order).
```

**Comment by lkeegan** [comment]
Turns out psychopy uses pyqt5, pyqt4, or wxWidgets in that order of preference.

I thought it used wx by default, so was directly wx using this while psychopy was using pyqt5.

So we should also use pyqt5 and see if that fixes this.

This also suggests that we could remove the wxWidgets dependency from psychopy on CI
